apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-formation
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
         tcpSocket:
           port: 8080
         initialDelaySeconds: 15
           periodSeconds: 10
        livenessProbe:
         tcpSocket:
            port: 8080
         initialDelaySeconds: 15
            periodSeconds: 10
        
        imagePullPolicy: IfNotPresent
