# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   labels:
#     run: nginx
#   name: nginx-ingress
#   namespace: k8s-formation
#   annotations:
#     #kubernetes.io/ingress.class: nginx
#     #nginx.ingress.kubernetes.io/proxy-body-size: "0"
#     # nginx.ingress.kubernetes.io/rewrite-target: /
#     #nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: external-lb
#   rules:
#   - host: labs.cadmus-it.com 
#     http:
#       paths:
#       - backend:
#           service:
#             name: nginx
#             port:
#               number: 8080
#         path: /
#         pathType: Prefix
#   tls:
#   - hosts:
#     - labs.cadmus-it.com
#     secretName: nginx-tls

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: k8s-formation
spec:
  gatewayClassName:  cluster-gateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---    
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-httproute
  namespace: k8s-formation
spec:
  parentRefs:
  - name: nginx-gateway
  hostnames:
  - "labs.cadmus-it.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx
      port: 8080
