apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: k8s-formation
spec:
  rules:
  - host: labs.cadmus-it.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  # Annotation pour l'émetteur ClusterIssuer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging